{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mku.salmon",
    "module": "salmon-core",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "salmon-core-2.0.0.jar",
          "url": "salmon-core-2.0.0.jar",
          "size": 51789,
          "sha512": "5fec9ec5053fc3c6f03700e5bf03e53076286b4d74fcac0ea77d811c3e5be349d059b5842644f97b16f962161f7bf26bc23d3566705de54a81d077d3ce376609",
          "sha256": "322b56e60bb0e1f8d3d80ad9323c3a061881c11c78d79a8cc3e8a143ab0259a8",
          "sha1": "e2236c7a23c9fa6ee9b3cc7c55de8a52a326b0d9",
          "md5": "40552484b89a608c5124768ab5464677"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "salmon-core-2.0.0.jar",
          "url": "salmon-core-2.0.0.jar",
          "size": 51789,
          "sha512": "5fec9ec5053fc3c6f03700e5bf03e53076286b4d74fcac0ea77d811c3e5be349d059b5842644f97b16f962161f7bf26bc23d3566705de54a81d077d3ce376609",
          "sha256": "322b56e60bb0e1f8d3d80ad9323c3a061881c11c78d79a8cc3e8a143ab0259a8",
          "sha1": "e2236c7a23c9fa6ee9b3cc7c55de8a52a326b0d9",
          "md5": "40552484b89a608c5124768ab5464677"
        }
      ]
    }
  ]
}
